name: Deploy Backend to Railway
on:
  push:
    branches: [main]
    paths:
      - "app/backend/**"
      - ".github/workflows/backend-action.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn
      - name: Lint
        run: yarn lint:backend
      - name: Test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: yarn test
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_BACKEND_SERVICE_ID: ${{ secrets.RAILWAY_BACKEND_SERVICE_ID }}
        run: railway up -d -s $RAILWAY_BACKEND_SERVICE_ID ./app/backend
